### ISSUE TITLE
Autoload type "files"

### ISSUE THREAD

**Issue by dmolineus** [phpcq/autoload-validation#2]
I'm currently switching from the former cca/build-system to phpcq. When using the autoload type _files_ (https://getcomposer.org/doc/04-schema.md#files) the autoload-validation fails. It would be nice if there is an option to ignore the autoload type _files_.

**Comment by tristanlins** [comment]
I'm not sure if this is a "bug" or a "feature". Maybe the files autoload is just not supported yet...

**Comment by discordier** [comment]
Yep, not supported yet.

**Comment by dmolineus** [comment]
I have no idea how the files type could be supported properly - meaning that the files loaded by the files autoloader are checked as well.

If you would accept an ignore configuration so that the autoload validation does not fail, I'll provide an PR. 

I use the files autoloader to load 3rd party files (Contao) which are required for the specs. So at the moment I have to exclude the autoload validation on this projectes.

**Comment by discordier** [comment]
Well, IMO the files should be locatable relative to the repository root (location of composer.json).
Otherwise they would not be loadable anyway.

Can you post a link to your composer.json so I can have a look at it?

**Comment by dmolineus** [comment]
Of course, for example I use the files autoloader in https://github.com/netzmacht/contao-toolkit/blob/master/composer.json. The autoload-validation is loaded by netzmacht/contao-build-tools which also provides the autoload.php being used.

It's only used to get Contao to work to mock their objects in the specs. So it's just a workaround because Contao does not provide an autoloading without calling the `initialize.php`

If you have any better solution for this issue, I would be glad if you let me know.

**Comment by discordier** [comment]
IMO your problems should all be solved as soon as we have implemented #3 in https://github.com/contao-community-alliance/composerized-contao-core as plain autoload section.

Am I wrong on this one?

**Comment by dmolineus** [comment]
Yes, it would solve it.

**Comment by discordier** [comment]
This has been fixed in 1.1.0 alpha.

Currently we have a BC layer in place which activates itself and will get removed in 2.0.

You may now register "hacks" to the autoloader.
These hacks are simple auto loader registering files that are capable of auto loading a class.
See example at: https://github.com/phpcq/autoload-validation/blob/5e22ffddbaf9f311b69f1986f81fa60b78417d81/hacks/contao-hack.php
