### ISSUE TITLE
Contao hack still in code

### ISSUE THREAD

**Issue by dmolineus** [phpcq/autoload-validation#3]
As the cca/build-system moved to a separate project, I propose to remove the [Contao autoloading hack](https://github.com/phpcq/autoload-validation/blob/master/src/Command/CheckAutoloading.php#L515-L529) from it. 

It could be added to an files autoloader in the `autoload-dev` section of the the Contao project.

**Comment by discordier** [comment]
@dmolineus pretty nice idea hacking it into the core.
Sadly I have no time to implement this into the modded core version atm and therefore this will have to wait some while.
In the meantime I'd rather leave it where it is for the moment.

**Comment by discordier** [comment]
@dmolineus Have a look at the new 1.1.0-alpha1 please and test it.
It includes support for hacks and the Contao loader is now deprecated.
